# Generated by Django 4.2.1 on 2023-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markmailuser',
            name='rescue_code',
            field=models.IntegerField(max_length=16),
        ),
    ]
