# Generated by Django 4.2.1 on 2023-06-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_alter_markmailuser_rescue_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='No Subject', max_length=100),
        ),
    ]
