# Generated by Django 4.2.1 on 2023-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('archived', 'Archived'), ('favourite', 'Favourite')], default='inbox', max_length=15),
        ),
    ]
