# Generated by Django 4.2.1 on 2023-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_email_isread_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(blank=True, choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('archived', 'Archived'), ('favourites', 'Favourites')], default='inbox', max_length=15, null=True),
        ),
    ]
