# Generated by Django 4.2.2 on 2023-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markmailuser',
            name='rescue_code',
            field=models.IntegerField(),
        ),
    ]
